[package]
name = "evm-logs-canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { version = "0.10" }
ic-cdk = "0.14.0"
ic-cdk-timers = "0.3" 
ic-cdk-macros = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
evm-rpc-canister-types = "0.1"


[package.metadata.candid]
generate = true