[package]
name = "evm-logs-canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { version = "0.9" }
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
evm_rpc_types = { git = "https://github.com/internet-computer-protocol/evm-rpc-canister", package = "evm_rpc_types" }



[package.metadata.candid]
generate = true